export const SET_GRADE_CATEGORY = "SET_GRADE_CATEGORY";
export const SET_PREASSESTMENT_SCORE = "SET_PREASSESTMENT_SCORE";
export const SET_ASSESTMENT_SCORE = "SET_ASSESTMENT_SCORE";
export const SET_ISDONE = "SET_ISDONE";
